### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by adiusz** [ccalamos/gatsby-source-googlemaps-static#16]
I run npm install of the plugin, paste this to the gatsby-config:

```
      resolve: `gatsby-source-googlemaps-static`,
      options: {
        key: process.env.GOOGLE_MAPS_STATIC_API_KEY,
        center: `53.2547023,19.0905782`,
```

 I also added API key to the .env file (which is working cause I have other API key there). Thing is when i run gatsby develop I got this:

```
 ERROR #11321  PLUGIN

"gatsby-source-googlemaps-static" threw an error while running the sourceNodes lifecycle:

Request failed with status code 403



  Error: Request failed with status code 403

  - createError.js:16 createError
    [gatsby-classic-theme]/[axios]/lib/core/createError.js:16:15

  - settle.js:17 settle
    [gatsby-classic-theme]/[axios]/lib/core/settle.js:17:12

  - http.js:236 IncomingMessage.handleStreamEnd
    [gatsby-classic-theme]/[axios]/lib/adapters/http.js:236:11

  - next_tick.js:63 process._tickCallback
    internal/process/next_tick.js:63:19


warn The gatsby-source-googlemaps-static plugin has generated no Gatsby nodes. Do you need it?
```

Should I provide more info or is this the plugin's fault?

**Comment by ccalamos** [comment]
The warning is correct because it errors out it will not generate anything. The error though is saying that path is forbidden, are you sure you are using the correct API key for Google Maps Static API?

**Comment by adiusz** [comment]
Sorry for late respond. 
Yep, I'm sure the key is correct. I literally use the same key with another lib in the same project + on few other websites. Also, after the frist error I posted up I have another about query. Just in case here it is:


```
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "staticMap" on type "Query".

If you don't expect "staticMap" to exist on the type "Query" it is most likely a typo.
However, if you expect "staticMap" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "staticMap" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
```

**Comment by ccalamos** [comment]
Well to quickly answer the second error, that error is being displayed because no Static Maps are being created so the data type staticMap in the query will not be created. So basically if we solve your 403 error then the second error should be resolved.

Let's try some things to figure this out...

https://maps.googleapis.com/maps/api/staticmap?center=Berkeley,CA&zoom=14&size=400x400&key=YOUR_API_KEY

Copy that URL and replace "YOUR_API_KEY" with your api key and paste that URL in the browser and let me know if you can see the map in your browser.

If that works then post your full config (with any sensitive data removed) here and I will try to help further.

**Comment by baart1989** [comment]
@adiusz give a try link that @ccalamos have sent.

Thankfully to that I was able to see full error, which in my case was.

> The Google Maps Platform server rejected your request. You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

Hope that helps!

**Comment by adiusz** [comment]
Now we know something. It's not working, I got this:
`The Google Maps Platform server rejected your request. This API project is not authorized to use this API.`
I will try later with another key.

**Comment by ccalamos** [comment]
https://developers.google.com/maps/gmp-get-started

This should help you get started
