### ISSUE TITLE
Coverage Test [google-sign-url.ts]

### ISSUE THREAD

**Issue by ccalamos** [ccalamos/gatsby-source-googlemaps-static#22]
Write coverage tests in Jest for `google-sign-url.ts` located in the `src` directory.

**Comment by ccalamos** [comment]
**IMPORTANT NOTE:** Test does not need 100% coverage for a PR to be accepted, any % increase will be accepted!

**Comment by Reghill** [comment]
Hi @ccalamos , can you please assign this issue to me? I can work on it.

**Comment by ccalamos** [comment]
Sounds good!
